export enum ExceptionCode {
  UNAUTHORIZED = 'UNAUTHORIZED_USER',
  FORBIDDEN = 'FORBIDDEN_ACCESS',
  NOT_FOUND = 'DATA_NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}
