export enum ExceptionCode {
  // System unhandled error
  INTERNAL_SERVER_ERROR = 'SYS00',

  // Database error
  DATABASE_CONNECTION_ERROR = 'DB00',

  // Authentication/Authorization Error
  UNAUTHORIZED_USER = 'AUT00',
  FORBIDDEN_ACCESS = 'AUT01',
  INVALID_CREDENTIALS = 'AUT02',
  INVALID_TOKEN = 'AUT03',
  EXPIRED_TOKEN = 'AUT04',
  REVOKED_TOKEN = 'AUT05',
  TOKEN_NOT_FOUND = 'AUT06',
  INVALID_TOKEN_TYPE = 'AUT07',
  EMAIL_NOT_VERIFIED = 'AUT08',
  INVALID_EMAIL_TOKEN = 'AUT09',

  // Request Error
  INVALID_REQUEST = 'REQ00',
  MISSING_REQUIRED_FIELDS = 'REQ01',
  INVALID_PARAMETERS = 'REQ02',
  INVALID_QUERY_PARAMETERS = 'REQ03',
  INVALID_PATH_PARAMETERS = 'REQ05',
  INVALID_HEADER_PARAMETERS = 'REQ06',
  TOO_MANY_REQUESTS = 'REQ07',
  UNPROCESSABLE_ENTITY = 'REQ08',

  // Data Error
  DATA_NOT_FOUND = 'DAT00',
  DATA_ALREADY_EXISTS = 'DAT01',

  // External Error
  EXTERNAL_CONNECTION_ERROR = 'EXT00',
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXT01',
  EXTERNAL_SERVICE_TIMEOUT = 'EXT02',
  EXTERNAL_SERVICE_ERROR = 'EXT03',
  EXTERNAL_SERVICE_UNAUTHORIZED = 'EXT04',
  EXTERNAL_SERVICE_FORBIDDEN = 'EXT05',
  EXTERNAL_SERVICE_NOT_FOUND = 'EXT06',
  EXTERNAL_SERVICE_INVALID_REQUEST = 'EXT07',
}
