name: Build and Deploy to VPS

on:
  push:
    branches:
      - dev # Ganti dengan branch lo kalau beda

permissions:
  contents: write
  pull-requests: write

jobs:
  release-dev:
    runs-on: ubuntu-latest
    environment: deploy-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Sesuaikan dengan versi node.js lo

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.9.0

      - name: Install dependencies
        run: |
          pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma:generate

      - name: Build NestJS application
        run: |
          pnpm build

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: |
            dist
            package.json
            pnpm-lock.yaml
          target: '/home/satukas-dev/satukas-api'

      - name: Upload .env to VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cat > /home/satukas-dev/satukas-api/.env <<'EOF'
            ${{ secrets.ENV_DEV }}
            EOF

      - name: Run application on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            source "$NVM_DIR/bash_completion"
            cd /home/satukas-dev/satukas-api
            rm -rf node_modules
            pnpm install
            pm2 restart satukas-api || pm2 start dist/main.js --name satukas-api
            pm2 save

      # Step baru buat nambahin label ke PR
      - name: Add label to PR
        if: success()
        run: |
          PR_NUMBER=$(gh pr list --base dev --head ${{ github.sha }} --json number --jq '.[0].number')
          if [ ! -z "$PR_NUMBER" ]; then
            gh pr edit $PR_NUMBER --add-label "release-dev"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
